[tool.poetry]
name = "conduit"
version = "0.1.0"
description = "Pyramid and OpenAPI3 based RealWorld.io example."
authors = ["niteo.co <info@niteo.co>"]
license = "MIT"
classifiers = [
	"Programming Language :: Python",
	"Programming Language :: Python :: 3.8",
	"Framework :: Pyramid",
	"Topic :: Internet :: WWW/HTTP",
	"Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
	"License :: MIT",
]
homepage = "http://github.com/teamniteo/pyramid-realworld-example-app"
keywords = ["pyramid", "openapi", "realworld"]
packages = [
	{ include = "conduit", from = "src" },
]

[tool.poetry.plugins."paste.app_factory"]
main = "conduit:main"
test_suite = "conduit"

[tool.poetry.dependencies]
python = "~3.8"

argon2-cffi = "*"
gunicorn = "*"
mypy_extensions = "*"
passlib = "*"
psycopg2-binary = "*"
pyramid = "<2.0"
pyramid_deferred_sqla = {git = "https://github.com/teamniteo/pyramid_deferred_sqla.git"}
pyramid_force_https = "*"
pyramid_heroku = "*"
pyramid_jwt = "*"
pyramid_openapi3 = "*"
pyramid_redirect = "*"
python-slugify = "*"
raven = "*"
structlog = "*"
sqlalchemy = "<1.4"

[tool.poetry.dev-dependencies]
bandit = "*"
black = "==20.8b1"
codespell = "*"
coverage = "*"
flake8 = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-comprehensions = "*"
flake8-debugger = "*"
flake8-deprecated = "*"
flake8-docstrings = "*"
flake8-isort = "*"
flake8-mock = "*"
flake8-mutable = "*"
flake8-plone-hasattr = "*"
flake8-print = "*"
flake8-self = "*"
flake8-super-call = "*"
flake8-tuple = "*"
freezegun = "*"
mypy = "*"
npm = "*"
pre-commit = "*"
pre-commit-hooks = "*"
pytest = "*"
pytest-bdd = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-randomly = "*"
pytest-testmon = "*"
pytest-watch = "*"
requests-html = "*"
responses = "*"
sqlalchemy-stubs = "*"
testfixtures = "*"
typecov = "*"
waitress = "*"
webtest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
